server:
  port: 0

spring:
  application:
    name: shopping-cart
  config:
    import: "configserver: "
  cloud:
    config:
      openfeign:
        circuitbreaker:
          enabled: true
      discovery:
        enabled: true
        serviceId: config-server
      fail-fast: true
      retry:
        useRandomPolicy: true
        max-interval: 6000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: circuitbreakers